apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubequery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/rorysavage77/KubeQuery
    path: helm/kubequery
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubequery
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: postgresqueries.kubequery.cloudnexus.io
