apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kedacore.github.io/charts'
    chart: keda
    targetRevision: 2.16.0 # Use the latest stable version
    helm:
      releaseName: keda
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Highly recommended for CRDs to avoid annotation length limits
